/* Bard Defines */
#define SONG_MINUET    0
#define SONG_MINNE     1
#define SONG_MADRIGAL  2
#define SONG_MARCH     3
#define SONG_REQUIEM   4
#define SONG_PAEON     5
#define SONG_BALLAD    6
#define SONG_LULLABY   7
#define SONG_HYMNUS    8
#define SONG_MASTERY   9
#define SONG_TRAVEL    10
#define BARD_LESSONS   11

/* Races -Xrakisis */
#define RACE_NONE		0
#define RACE_HUMAN		1
#define RACE_ELF		2
#define	RACE_GNOME		3
#define RACE_GULLYDWARF		4
#define RACE_HILLDWARF		5
#define RACE_MTDWARF		6
#define RACE_DRAGONKIND		7
#define RACE_HOBBIT		8
#define RACE_KENDER		9
#define RACE_DROW		10
#define RACE_GIANT		11
#define RACE_HALFELF		12
#define RACE_OGRE		13
#define RACE_HALFOGRE		14
#define RACE_MINOTAUR		15
#define RACE_GOBLIN		16
#define RACE_HOBGOBLIN		17 
#define RACE_DUERGARDWARF	18
#define	RACE_TROLL		19
#define RACE_HALFTROLL		20
#define RACE_ORC		21
#define RACE_HALFORC		22
#define RACE_CENTAUR		23
#define RACE_WILDELF		24
#define RACE_ARCHDEMON		25
#define RACE_ARCHANGEL		26
#define RACE_AQUATICELF		27
#define RACE_DESERTELF		28
#define RACE_FIREELF		29
#define RACE_GHOSTELF		30
#define RACE_GRAYELF		31
#define RACE_JUNGLEELF		32
#define RACE_WOODELF		33
#define RACE_AQUATICDWARF	34
#define RACE_ARCTICDWARF	35
#define RACE_DEEPDWARF		36
#define RACE_DESERTDWARF	37
#define RACE_DREAMDWARF		38
#define RACE_EARTHDWARF		39
#define RACE_GOLDDWARF		40
#define RACE_GREYDWARF		41
#define RACE_JUNGLEDWARF	42
#define RACE_AQUATICKOBOLD	43
#define RACE_ARCTICKOBOLD	44
#define RACE_DESERTKOBOLD	45
#define RACE_EARTHKOBOLD	46
#define RACE_JUNGLEKOBOLD	47
#define RACE_GNOLL		48
#define RACE_HILLGIANT		49
#define RACE_FIREGIANT		50
#define RACE_FROSTGIANT		51
	
#define RACE_PIXIE		52
#define RACE_AIRGNOME		53
#define RACE_AQUATICGNOME	54
#define RACE_ARCTICGNOME	55
#define RACE_CHAOSGNOME		56
#define RACE_DEEPGNOME		57
#define RACE_DESERTGNOME	58
#define RACE_FORESTGNOME	59
#define RACE_JUNGLEGNOME	60
#define RACE_ROCKGNOME		61
#define RACE_BUGBEAR		62
#define RACE_AIRGOBLIN		63
#define RACE_AQUATICGOBLIN	64
#define RACE_ARCTICGOBLIN	65
#define RACE_GOBLINFORESTKITH	66
#define RACE_JUNGLEGOBLIN	67
#define RACE_OGREMAGE		68
#define RACE_DESERTGOBLIN	69
#define RACE_ARCTICELF		70










